Traceback (most recent call last):
  File "/group/40034/yaoweili/code/guided-diffusion/evaluations/genrate_data.py", line 21, in <module>
    X_train, Y_train = load_raw_data(data_path, img_size=64) 
  File "/group/40034/yaoweili/code/guided-diffusion/evaluations/utils.py", line 45, in load_raw_data
    d = unpickle(data_flie)
  File "/group/40034/yaoweili/code/guided-diffusion/evaluations/utils.py", line 8, in unpickle
    with open(file, 'rb') as fo:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/imagenet64/imagenet64_pickle/train_data_batch_0'
